spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zoozoo_bank
    username: root
    password: 110811
  profiles:
    active: dev

logging:
  level:
    root: info
    com.prgrms.zoozoobank: debug

server:
  port: 8080

info:
  app:
    name: ZooZooBank
    description: "A banking application"
    version: "1.0.0"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
